[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[redirects]]
from = "https://nomadic.netlify.com/*"
to = "https://www.nomadic.co.id/:splat"
status = 301
force = true


[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Robots-Tag = "index, follow"
